//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translanza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.RolMenu = new HashSet<RolMenu>();
            this.RolMenu1 = new HashSet<RolMenu>();
        }
    
        public int RowID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Controlador { get; set; }
        public string Metodo { get; set; }
        public Nullable<int> TipoMenuID { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual ICollection<RolMenu> RolMenu { get; set; }
        public virtual ICollection<RolMenu> RolMenu1 { get; set; }
    }
}
