//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translanza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tercero
    {
        public Tercero()
        {
            this.AfiliadoConductor = new HashSet<AfiliadoConductor>();
            this.AfiliadoConductor1 = new HashSet<AfiliadoConductor>();
            this.EspecialidadConductor = new HashSet<EspecialidadConductor>();
            this.ObservacionConductor = new HashSet<ObservacionConductor>();
            this.Usuario = new HashSet<Usuario>();
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Img_DocIdentidad { get; set; }
        public string Img_LicenciaConduccion { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<int> TipoID { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual ICollection<AfiliadoConductor> AfiliadoConductor { get; set; }
        public virtual ICollection<AfiliadoConductor> AfiliadoConductor1 { get; set; }
        public virtual ICollection<EspecialidadConductor> EspecialidadConductor { get; set; }
        public virtual ICollection<ObservacionConductor> ObservacionConductor { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
