//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translanza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public Tipo()
        {
            this.EspecialidadConductor = new HashSet<EspecialidadConductor>();
            this.Tercero = new HashSet<Tercero>();
            this.Vehiculo = new HashSet<Vehiculo>();
            this.Vehiculo1 = new HashSet<Vehiculo>();
            this.Vehiculo2 = new HashSet<Vehiculo>();
            this.Vehiculo3 = new HashSet<Vehiculo>();
            this.Vehiculo4 = new HashSet<Vehiculo>();
            this.Menu = new HashSet<Menu>();
        }
    
        public int RowID { get; set; }
        public int AgrupacionID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Valor { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Agrupacion Agrupacion { get; set; }
        public virtual ICollection<EspecialidadConductor> EspecialidadConductor { get; set; }
        public virtual ICollection<Tercero> Tercero { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo1 { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo2 { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo3 { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo4 { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
    }
}
